import type {
  ActivityEvent,
  Family,
  FamilyMember,
  Reward,
  Task,
} from "./types";

export const demoFamily: Family = {
  id: "family-demo",
  name: "Наша семья",
  memberIds: ["masha", "natasha", "vanya"],
  pointsRules: {
    difficultyDefaults: { easy: 15, normal: 30, hard: 70, epic: 150 },
  },
  notificationRules: {
    notifyOnComplete: true,
    notifyOnRefuse: true,
    notifyOnPostpone: false,
    notifyOnMissed: true,
    notifyOnBadge: true,
    notifyOnReward: true,
    maxAutoReminders: 3,
    followUpDelaysMinutes: [60, 180],
  },
  createdAt: "2026-01-01T00:00:00.000Z",
};

export const demoMembers: FamilyMember[] = [
  {
    id: "masha",
    familyId: "family-demo",
    displayName: "Маша",
    photoUrl: null,
    accentColor: "pink",
    points: 620,
    lifetimePoints: 2620,
    currentStreak: 7,
    longestStreak: 14,
    completedTaskCount: 12,
    timezone: "Europe/Moscow",
    active: true,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "natasha",
    familyId: "family-demo",
    displayName: "Наташа",
    photoUrl: null,
    accentColor: "lilac",
    points: 480,
    lifetimePoints: 1980,
    currentStreak: 3,
    longestStreak: 9,
    completedTaskCount: 9,
    timezone: "Europe/Moscow",
    active: true,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "vanya",
    familyId: "family-demo",
    displayName: "Ваня",
    photoUrl: null,
    accentColor: "sky",
    points: 310,
    lifetimePoints: 1310,
    currentStreak: 2,
    longestStreak: 5,
    completedTaskCount: 6,
    timezone: "Europe/Moscow",
    active: true,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
];

export const demoTasksToday: Task[] = [
  {
    id: "t-homework",
    familyId: "family-demo",
    title: "Уроки",
    category: "school",
    icon: "homework",
    color: "lilac",
    points: 50,
    difficulty: "hard",
    assignee: { kind: "member", memberIds: ["vanya"] },
    creatorId: "vanya",
    recurrence: { type: "weekdays" },
    dueTime: "15:00",
    hasDeadline: true,
    reminderEnabled: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "t-kitchen",
    familyId: "family-demo",
    title: "Убрать кухню",
    category: "household",
    icon: "kitchen",
    color: "yellow",
    points: 30,
    difficulty: "normal",
    assignee: { kind: "member", memberIds: ["natasha"] },
    creatorId: "natasha",
    recurrence: { type: "daily" },
    dueTime: "18:00",
    hasDeadline: true,
    reminderEnabled: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "t-cat",
    familyId: "family-demo",
    title: "Покормить кота",
    category: "pet",
    icon: "cat",
    color: "pink",
    points: 20,
    difficulty: "easy",
    assignee: { kind: "member", memberIds: ["masha"] },
    creatorId: "masha",
    recurrence: { type: "daily" },
    dueTime: "20:00",
    hasDeadline: true,
    reminderEnabled: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "t-no-gadgets",
    familyId: "family-demo",
    title: "Вечер без гаджетов",
    category: "family",
    icon: "phone-off",
    color: "coral",
    points: 80,
    difficulty: "hard",
    assignee: { kind: "family" },
    creatorId: "masha",
    recurrence: { type: "daily" },
    startTime: "21:00",
    hasDeadline: false,
    reminderEnabled: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "t-shower",
    familyId: "family-demo",
    title: "Душ",
    category: "hygiene",
    icon: "shower",
    color: "lilac",
    points: 20,
    difficulty: "easy",
    assignee: { kind: "member", memberIds: ["vanya"] },
    creatorId: "vanya",
    recurrence: { type: "times_per_week", timesPerWeek: 3 },
    dueTime: "22:00",
    hasDeadline: true,
    reminderEnabled: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
];

export const demoFamilyReward: Reward = {
  id: "r-family-1000",
  familyId: "family-demo",
  name: "Мини-подарок от семьи",
  icon: "gift",
  pointsRequired: 1000,
  scope: "family",
  redeemed: false,
  isMilestone: true,
};

export const demoFamilyPoints = 710;

export const demoActivity: ActivityEvent[] = [
  {
    id: "a-1",
    familyId: "family-demo",
    type: "task_completed",
    memberId: "masha",
    taskId: "t-cat",
    points: 20,
    message: "Маша выполнила «Покормить кота»",
    createdAt: "2026-09-19T21:50:00.000Z",
  },
  {
    id: "a-2",
    familyId: "family-demo",
    type: "task_completed",
    memberId: "natasha",
    taskId: "t-kitchen",
    points: 30,
    message: "Наташа убрала кухню",
    createdAt: "2026-09-19T21:00:00.000Z",
  },
  {
    id: "a-3",
    familyId: "family-demo",
    type: "task_completed",
    memberId: "vanya",
    taskId: "t-homework",
    points: 50,
    message: "Ваня сделал уроки",
    createdAt: "2026-09-19T19:50:00.000Z",
  },
];
